CREATE DATABASE  IF NOT EXISTS `astore2` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `astore2`;
create table category (ID integer generated by default as identity, NAME varchar(45), primary key (ID))
create table customer_order (ID integer generated by default as identity, AMOUNT decimal(19,2) not null, CONFIRMATION_NUMBER integer not null, DATE_CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null, EMAIL varchar(254) not null, FIRST_NAME varchar(45) not null, LAST_NAME varchar(45) not null, PHONE varchar(45) not null, ROUTE_ID integer not null, USER_ID integer, primary key (ID))
create table dogs (id bigint generated by default as identity, DATE_CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null, name varchar(255), primary key (id))
create table ordered_ticket (ID integer generated by default as identity, DOB date, FIRST_NAME varchar(30), LAST_NAME varchar(40), LICENSE_PLATE varchar(10), MIDDLE_NAME varchar(30), SUPPORTING_DOCUMENT_DATA varchar(1024) not null, CUSTOMER_ORDER_ID integer not null, SUPPORTING_DOCUMENT_ID integer not null, TICKET_ID integer not null, primary key (ID))
create table role (ID integer generated by default as identity, NAME varchar(45) not null, primary key (ID))
create table route (ID integer generated by default as identity, NAME varchar(45) not null, primary key (ID))
create table supporting_document (ID integer generated by default as identity, DOC_TYPE integer not null, NAME varchar(45) not null, CATEGORY_ID integer not null, primary key (ID))
create table ticket (ID integer generated by default as identity, DATA_LABEL varchar(256), DESCRIPTION varchar(255) not null, LAST_UPDATE timestamp not null, NAME varchar(45) not null, PRICE decimal(19,2) not null, CATEGORY_ID integer not null, primary key (ID))
create table user (ID integer generated by default as identity, ACTIVE boolean not null, DATE_CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null, FIRST_NAME varchar(45) not null, LAST_NAME varchar(45) not null, PASSWORD varchar(64), PHONE varchar(45) not null, SALT varchar(64), TOKEN varchar(64), USERNAME varchar(254) not null, primary key (ID))
create table user_has_role (ROLE_ID integer not null, USER_ID integer not null)
alter table customer_order add constraint FK_f3wqm9glngce8xg071k7hj2do foreign key (ROUTE_ID) references route
alter table customer_order add constraint FK_81u7kl8prfglehqcdeo35e1ed foreign key (USER_ID) references user
alter table ordered_ticket add constraint FK_83j9fmexocrbdjixv291g98us foreign key (CUSTOMER_ORDER_ID) references customer_order
alter table ordered_ticket add constraint FK_ex62tlljacj82oyi7cr3qwtmn foreign key (SUPPORTING_DOCUMENT_ID) references supporting_document
alter table ordered_ticket add constraint FK_imk320ude23dt1mbaq8ou2on6 foreign key (TICKET_ID) references ticket
alter table supporting_document add constraint FK_s75iwaacxb429cd33v9p11utw foreign key (CATEGORY_ID) references category
alter table ticket add constraint FK_ahptiythhmn3fhjx17tc86xm7 foreign key (CATEGORY_ID) references category
alter table user_has_role add constraint FK_mj0c2gr0k35hgw9e8hxnuqce6 foreign key (USER_ID) references user
alter table user_has_role add constraint FK_nuppelwf81k1bgo6410kt5352 foreign key (ROLE_ID) references role
